"""tsumuki 0.2.0

Revision ID: a973caa15311
Revises: 
Create Date: 2026-09-27 10:07:44.263820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a973caa15311'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS status;")  # 防止 status 类型已存在冲突
    op.create_table('storages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('ref_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'FINISHED', 'FAILED', name='status'), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('last_chunk_size', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index('ix_storages_cleanup_timeout', 'storages', ['status', 'modified_at'], unique=False, postgresql_where=sa.text("status IN ('UPLOADING', 'FAILED')"))
    op.create_index('ix_storages_orphan', 'storages', ['status', 'ref_count', 'modified_at'], unique=False, postgresql_where=sa.text("status = 'FINISHED' AND ref_count = 0"))
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_space', sa.BigInteger(), nullable=False),
    sa.Column('used_space', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dirs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['dirs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_dirs_parent_id'), 'dirs', ['parent_id'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pwd', sa.String(length=6), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_shares_expires_at'), 'shares', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shares_storage_id'), 'shares', ['storage_id'], unique=False)
    op.create_index(op.f('ix_shares_user_id'), 'shares', ['user_id'], unique=False)
    op.create_table('trashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_path', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trashes_expires_at'), 'trashes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_trashes_storage_id'), 'trashes', ['storage_id'], unique=False)
    op.create_index(op.f('ix_trashes_user_id'), 'trashes', ['user_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('dir_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dir_id'], ['dirs.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dir_id', 'name', name='uq_dir_filename_status')
    )
    op.create_index(op.f('ix_files_storage_id'), 'files', ['storage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_storage_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_trashes_user_id'), table_name='trashes')
    op.drop_index(op.f('ix_trashes_storage_id'), table_name='trashes')
    op.drop_index(op.f('ix_trashes_expires_at'), table_name='trashes')
    op.drop_table('trashes')
    op.drop_index(op.f('ix_shares_user_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_storage_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_expires_at'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_dirs_parent_id'), table_name='dirs')
    op.drop_table('dirs')
    op.drop_table('users')
    op.drop_index('ix_storages_orphan', table_name='storages', postgresql_where=sa.text("status = 'FINISHED' AND ref_count = 0"))
    op.drop_index('ix_storages_cleanup_timeout', table_name='storages', postgresql_where=sa.text("status IN ('UPLOADING', 'FAILED')"))
    op.drop_table('storages')
    # ### end Alembic commands ###
