"""tsumiki_db 0.1.0

Revision ID: b1a6e0db4c9f
Revises: 
Create Date: 2026-05-08 15:46:14.175351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a6e0db4c9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('ref_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'FINISHED', 'FAILED', name='status'), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('last_chunk_size', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_chunk_index'), 'storage', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_storage_ref_count'), 'storage', ['ref_count'], unique=False)
    op.create_index(op.f('ix_storage_sha256'), 'storage', ['sha256'], unique=True)
    op.create_index(op.f('ix_storage_status'), 'storage', ['status'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_space', sa.Integer(), nullable=False),
    sa.Column('used_space', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('dir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['dir.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dir_parent_id'), 'dir', ['parent_id'], unique=False)
    op.create_index(op.f('ix_dir_path'), 'dir', ['path'], unique=True)
    op.create_index(op.f('ix_dir_user_id'), 'dir', ['user_id'], unique=False)
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('dir_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dir_id'], ['dir.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dir_id', 'name', name='uq_dir_filename_status')
    )
    op.create_index(op.f('ix_file_dir_id'), 'file', ['dir_id'], unique=False)
    op.create_index(op.f('ix_file_name'), 'file', ['name'], unique=False)
    op.create_index(op.f('ix_file_sha256'), 'file', ['sha256'], unique=False)
    op.create_index(op.f('ix_file_storage_id'), 'file', ['storage_id'], unique=False)
    op.create_index(op.f('ix_file_user_id'), 'file', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_user_id'), table_name='file')
    op.drop_index(op.f('ix_file_storage_id'), table_name='file')
    op.drop_index(op.f('ix_file_sha256'), table_name='file')
    op.drop_index(op.f('ix_file_name'), table_name='file')
    op.drop_index(op.f('ix_file_dir_id'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_dir_user_id'), table_name='dir')
    op.drop_index(op.f('ix_dir_path'), table_name='dir')
    op.drop_index(op.f('ix_dir_parent_id'), table_name='dir')
    op.drop_table('dir')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_storage_status'), table_name='storage')
    op.drop_index(op.f('ix_storage_sha256'), table_name='storage')
    op.drop_index(op.f('ix_storage_ref_count'), table_name='storage')
    op.drop_index(op.f('ix_storage_chunk_index'), table_name='storage')
    op.drop_table('storage')
    # ### end Alembic commands ###
